"""Formula models, generalized linear models, ANOVA, and post-fit analysis."""

from ._model_anova import ANOVATermResult, FactorialANOVAResult, factorial_anova
from ._model_design import (
    DesignMatrix,
    FactorEncoding,
    FormulaTerm,
    SumContrast,
    TreatmentContrast,
    design_matrix,
    parse_formula,
)
from ._model_glm import (
    BinomialFamily,
    GammaFamily,
    GaussianFamily,
    GLMFamily,
    GLMResult,
    IdentityLink,
    InverseLink,
    Link,
    LogitLink,
    LogLink,
    NegativeBinomialFamily,
    PoissonFamily,
    ProbitLink,
    QuasiBinomialFamily,
    QuasiPoissonFamily,
    glm,
    resolve_family,
)
from ._model_linear import FormulaRegressionResult, linear_model
from ._model_postfit import (
    CoefficientContrastResult,
    EstimatedMarginalMeansResult,
    JointWaldResult,
    MarginalMean,
    ModelComparisonResult,
    ModelComparisonRow,
    ancova,
    coefficient_contrast,
    compare_models,
    estimated_marginal_means,
    joint_wald_test,
)

__all__ = [
    "ANOVATermResult",
    "BinomialFamily",
    "CoefficientContrastResult",
    "DesignMatrix",
    "EstimatedMarginalMeansResult",
    "FactorEncoding",
    "FactorialANOVAResult",
    "FormulaRegressionResult",
    "FormulaTerm",
    "GLMFamily",
    "GLMResult",
    "GammaFamily",
    "GaussianFamily",
    "IdentityLink",
    "InverseLink",
    "JointWaldResult",
    "Link",
    "LogLink",
    "LogitLink",
    "MarginalMean",
    "ModelComparisonResult",
    "ModelComparisonRow",
    "NegativeBinomialFamily",
    "PoissonFamily",
    "ProbitLink",
    "QuasiBinomialFamily",
    "QuasiPoissonFamily",
    "SumContrast",
    "TreatmentContrast",
    "ancova",
    "coefficient_contrast",
    "compare_models",
    "design_matrix",
    "estimated_marginal_means",
    "factorial_anova",
    "glm",
    "joint_wald_test",
    "linear_model",
    "parse_formula",
    "resolve_family",
]
