"""User-facing statistical estimation, testing, and modeling namespace.

The facade re-exports common statistical workflows. Specialist APIs remain in
``descriptive``, ``estimation``, ``testing``, ``inference``, and ``modeling``.
"""

from . import descriptive, estimation, inference, modeling, testing
from .descriptive import (
    DescriptiveSummary,
    EmpiricalDistribution,
    correlation,
    covariance,
    describe,
    interquartile_range,
    kurtosis,
    mean,
    median,
    median_absolute_deviation,
    quantile,
    skewness,
    standard_deviation,
    trimmed_mean,
    variance,
    winsorize,
)
from .estimation import EstimationResult, maximum_likelihood, method_of_moments
from .inference import (
    ANOVAResult,
    MultipleTestingResult,
    RegressionResult,
    adjust_pvalues,
    bootstrap,
    kruskal_wallis_test,
    likelihood,
    linear_regression,
    mann_whitney_u_test,
    permutation_test,
    profile_likelihood,
    robust_regression_covariance,
    wilcoxon_signed_rank_test,
)
from .modeling import (
    FormulaRegressionResult,
    GLMResult,
    ancova,
    coefficient_contrast,
    compare_models,
    estimated_marginal_means,
    factorial_anova,
    glm,
    joint_wald_test,
    linear_model,
)
from .testing import (
    EquivalenceTestResult,
    HypothesisTestResult,
    bartlett_test,
    chi_square_goodness_of_fit,
    chi_square_independence,
    exact_binomial_test,
    kendall_tau_test,
    levene_test,
    one_proportion_z_test,
    one_sample_t_test,
    one_sample_z_test,
    paired_t_test,
    pearson_correlation_test,
    spearman_correlation_test,
    two_proportion_z_test,
    welch_t_test,
)

__all__ = [
    "ANOVAResult",
    "DescriptiveSummary",
    "EmpiricalDistribution",
    "EquivalenceTestResult",
    "EstimationResult",
    "FormulaRegressionResult",
    "GLMResult",
    "HypothesisTestResult",
    "MultipleTestingResult",
    "RegressionResult",
    "adjust_pvalues",
    "ancova",
    "bartlett_test",
    "bootstrap",
    "chi_square_goodness_of_fit",
    "chi_square_independence",
    "coefficient_contrast",
    "compare_models",
    "correlation",
    "covariance",
    "describe",
    "descriptive",
    "estimated_marginal_means",
    "estimation",
    "exact_binomial_test",
    "factorial_anova",
    "glm",
    "inference",
    "interquartile_range",
    "joint_wald_test",
    "kendall_tau_test",
    "kruskal_wallis_test",
    "kurtosis",
    "levene_test",
    "likelihood",
    "linear_model",
    "linear_regression",
    "mann_whitney_u_test",
    "maximum_likelihood",
    "mean",
    "median",
    "median_absolute_deviation",
    "method_of_moments",
    "modeling",
    "one_proportion_z_test",
    "one_sample_t_test",
    "one_sample_z_test",
    "paired_t_test",
    "pearson_correlation_test",
    "permutation_test",
    "profile_likelihood",
    "quantile",
    "robust_regression_covariance",
    "skewness",
    "spearman_correlation_test",
    "standard_deviation",
    "testing",
    "trimmed_mean",
    "two_proportion_z_test",
    "variance",
    "welch_t_test",
    "wilcoxon_signed_rank_test",
    "winsorize",
]


def __dir__():
    """Return the supported statistical discovery surface."""
    return sorted(__all__)
