"""Classical hypothesis tests with structured results."""

from ._testing_core import HypothesisTestResult
from ._testing_dependence import (
    MultivariateNormalityResult,
    cramers_v,
    distance_correlation,
    distance_correlation_test,
    kendall_tau,
    kendall_tau_test,
    spearman_correlation,
    spearman_correlation_test,
)
from ._testing_diagnostics import (
    autocorrelation,
    box_m_test,
    box_pierce_test,
    durbin_watson,
    hotelling_t2_test,
    ljung_box_test,
    mardia_normality_test,
    two_sample_hotelling_t2_test,
)
from ._testing_parametric import (
    EquivalenceTestResult,
    chi_square_goodness_of_fit,
    chi_square_independence,
    exact_binomial_test,
    one_proportion_z_test,
    one_sample_t_test,
    one_sample_z_test,
    paired_t_test,
    pearson_correlation_test,
    two_proportion_z_test,
    welch_t_test,
)
from ._testing_variance import (
    bartlett_test,
    brown_forsythe_test,
    levene_test,
    noninferiority_t_test,
    one_sample_tost,
    one_sample_variance_test,
    proportion_noninferiority_z_test,
    two_proportion_tost,
    variance_ratio_test,
    welch_tost,
)

__all__ = [
    "EquivalenceTestResult",
    "HypothesisTestResult",
    "MultivariateNormalityResult",
    "autocorrelation",
    "bartlett_test",
    "box_m_test",
    "box_pierce_test",
    "brown_forsythe_test",
    "chi_square_goodness_of_fit",
    "chi_square_independence",
    "cramers_v",
    "distance_correlation",
    "distance_correlation_test",
    "durbin_watson",
    "exact_binomial_test",
    "hotelling_t2_test",
    "kendall_tau",
    "kendall_tau_test",
    "levene_test",
    "ljung_box_test",
    "mardia_normality_test",
    "noninferiority_t_test",
    "one_proportion_z_test",
    "one_sample_t_test",
    "one_sample_tost",
    "one_sample_variance_test",
    "one_sample_z_test",
    "paired_t_test",
    "pearson_correlation_test",
    "proportion_noninferiority_z_test",
    "spearman_correlation",
    "spearman_correlation_test",
    "two_proportion_tost",
    "two_proportion_z_test",
    "two_sample_hotelling_t2_test",
    "variance_ratio_test",
    "welch_t_test",
    "welch_tost",
]
