"""Optional JAX Bayesian neural-network regression layer."""

from .core import (
    FrozenRegressionNetwork,
    JAXRegressionNetwork,
    JAXUnavailableError,
    NeuralNetworkFit,
    NeuralNetworkState,
    NeuralPredictive,
    RegressionNetworkConfig,
    TrainingHistory,
    alpha_divergence_loss,
    batchnorm_to_chain,
    extract_regression_network,
    fit_regression_network,
    flatten_parameters,
    gaussian_loss,
    gaussian_negative_log_likelihood,
    log_mean_exp,
    network_objective,
    network_regularization_loss,
    regression_loss,
    regression_network,
    sample_trained_network,
)

__all__ = [
    "FrozenRegressionNetwork",
    "JAXRegressionNetwork",
    "JAXUnavailableError",
    "NeuralNetworkFit",
    "NeuralNetworkState",
    "NeuralPredictive",
    "RegressionNetworkConfig",
    "TrainingHistory",
    "alpha_divergence_loss",
    "batchnorm_to_chain",
    "extract_regression_network",
    "fit_regression_network",
    "flatten_parameters",
    "gaussian_loss",
    "gaussian_negative_log_likelihood",
    "log_mean_exp",
    "network_objective",
    "network_regularization_loss",
    "regression_loss",
    "regression_network",
    "sample_trained_network",
]
